version: '3.8'

services:
  frontend:
    build: ./frontend
    image: carbon-tax-ledger-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    restart: always

  backend:
    build: ./backend
    image: carbon-tax-ledger-backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    restart: always

networks:
  default:
    driver: bridge