version: '3.8'

services:
  frontend:
    build: ./frontend
    image: carbon-tax-ledger-frontend
    ports:
      - "5173:5173"

  backend:
    build: ./backend
    image: carbon-tax-ledger-backend
    ports:
      - "5000:5000"
    environment:
      - PEER_ENDPOINT_ORG1MSP=host.docker.internal:7051
      - PEER_ENDPOINT_ORG2MSP=host.docker.internal:9051

  oracle:
    build: ./oracle
    image: carbon-tax-ledger-oracle
    environment:
      - PEER_ENDPOINT_ORG1MSP=host.docker.internal:7051
      - PEER_ENDPOINT_ORG2MSP=host.docker.internal:9051
    volumes:
      - ./test-network:/test-network